### ISSUE TITLE
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: upstream

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Cloak#30]
https://bpaste.net/YNBA

**Comment by Fuyukai** [comment]
https://gist.github.com/Fuyukai/8c206b0e0ca969cbe92ce84e5dccfecd you want to use this because the bpaste link expires in a day

**Comment by natanfudge** [comment]
As of 1.2.1, the remote will be created if it doesn't exist.
